CREATE DATABASE tradoc;
user tradoc;

CREATE TABLE role(
ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
ROLE_NAME VARCHAR(20) NOT NULL,
ROLE_DESC VARCHAR(50)
);
INSERT INTO `role` VALUES (1,'1','STAFF'),(2,'2','ADMIN'),(3,'3','ADMIN-2');

CREATE TABLE office(
OF_ID INT AUTO_INCREMENT PRIMARY KEY,
OF_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE users(
USER_ID INT PRIMARY KEY AUTO_INCREMENT,
USER_SN VARCHAR(20) NOT NULL,
USER_NAME VARCHAR(20) NOT NULL,
USER_FNAME VARCHAR(30) NOT NULL,
USER_LNAME VARCHAR(30) NOT NULL,
USER_OFC INT NOT NULL,
USER_PW VARCHAR(32) NOT NULL,
ROLE_ID INT NOT NULL DEFAULT 1,
USER_LOCK INT NOT NULL DEFAULT 1,
USER_PW_ATTEMPT INT NOT NULL DEFAULT 0,
USER_ONLINE INT NOT NULL DEFAULT 0
);

CREATE TABLE file(
F_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
F_TRACK_NO varchar(30) NOT NULL,
F_NAME_SERVER varchar(100) NOT NULL,
F_NAME_ORIG varchar(100) NOT NULL,
F_UPLOAD_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
F_DATE_LAST_CHECKED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
F_DESC varchar(200),
F_UPLOADER int NOT NULL,
F_OFFICE varchar(10) NOT NULL,
F_TAGS varchar(200),
FILE_X int(11) DEFAULT '0'
);

CREATE TABLE messages(
M_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
M_SENDER INT NOT NULL,
M_MSG VARCHAR(200) NOT NULL,
M_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
M_RCVR INT NOT NULL,
M_READ INT NOT NULL DEFAULT 0
);

CREATE TABLE pinned(
PIN_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
PIN_USER INT NOT NULL,
PIN_FILE INT NOT NULL,
PIN_NICKNAME VARCHAR(50)
);


CREATE TABLE activity(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
UID INT NOT NULL,
TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ACT_NAME VARCHAR(50) NOT NULL,
ACT_OBJECT VARCHAR(200),
IP_ADDR VARCHAR(20)
);
-- (ACT_NAME) VALUES('login'),('access'),('download'),('upload'),('query'),('modify'),('pin')

CREATE TABLE ok_files(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
EXT VARCHAR(4) NOT NULL
);
INSERT INTO ok_files (EXT) values('docx'),( 'doc'),( 'ppt'),( 'pptx'),( 'xls'),( 'xlsx'),( 'pdf'),( 'txt'),( 'odt'),( 'ods'),( 'odp'),('psd'),('mp4'),('wmv'),('avi');
INSERT INTO ok_files (EXT) values('avi'),( 'mp4'),( 'wmv'),( 'psd');
INSERT INTO `office` VALUES (1,'G6'),(2,'G1'),(3,'G2'),(4,'G3'),(5,'G4'),(6,'G5'),(7,'SDO'),(8,'OIG'),(9,'G7'),(10,'GADO'),(11,'SGS'),(12,'MFO'),(13,'CREO'),(14,'CPM'),(15,'CS4'),(16,'CRO'),(17,'GSMD'),(18,'OCE'),(19,'OCA'),(20,'Deputy Ofc'),(21,'OCS'),(22,'OC'),(23,'OCSM'),(24,'OCIG'),(25,'OCC');
INSERT INTO users(USER_SN,USER_NAME,USER_LNAME,USER_FNAME,USER_OFC,USER_PW,ROLE_ID,USER_LOCK)
VALUES('312442','admin','Lacson','Ghil',1,md5('password'),1,0);