CREATE DATABASE tradoc;
user tradoc;

CREATE TABLE role(
ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
ROLE_NAME VARCHAR(20) NOT NULL,
ROLE_DESC VARCHAR(50)
);
INSERT INTO role(ROLE_NAME, ROLE_DESC) values(1,'STAFF'),(2,'ADMIN');

CREATE TABLE office(
OF_ID INT AUTO_INCREMENT PRIMARY KEY,
OF_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE users(
USER_ID INT PRIMARY KEY AUTO_INCREMENT,
USER_SN VARCHAR(20) NOT NULL,
USER_NAME VARCHAR(20) NOT NULL,
USER_FNAME VARCHAR(30) NOT NULL,
USER_LNAME VARCHAR(30) NOT NULL,
USER_OFC INT NOT NULL,
USER_PW VARCHAR(32) NOT NULL,
ROLE_ID INT NOT NULL DEFAULT 1,
USER_LOCK INT NOT NULL DEFAULT 1,
USER_PW_ATTEMPT INT NOT NULL DEFAULT 0,
USER_ONLINE INT NOT NULL DEFAULT 0,
FOREIGN KEY users(USER_OFC) REFERENCES office(OF_ID)
);

CREATE TABLE file(
F_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
F_TRACK_NO varchar(30) NOT NULL,
F_NAME_SERVER varchar(100) NOT NULL,
F_NAME_ORIG varchar(100) NOT NULL,
F_UPLOAD_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
F_DATE_LAST_CHECKED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
F_DESC varchar(200) DEFAULT NULL,
F_UPLOADER int) NOT NULL,
F_OFFICE varchar(10) NOT NULL,
F_TAGS varchar(200) DEFAULT NULL,
FILE_X int(11) DEFAULT '0',
FOREIGN KEY file(F_UPLOADER) REFERENCES users(USER_ID),
FOREIGN KEY file(F_OFFICE) REFERENCES office(OF_ID)
);

CREATE TABLE messages(
M_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
M_SENDER INT NOT NULL,
M_MSG VARCHAR(200) NOT NULL,
M_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
M_RCVR INT NOT NULL,
M_READ INT NOT NULL DEFAULT 0,
FOREIGN KEY messages(M_SENDER) REFERENCES users(USER_ID),
FOREIGN KEY messages(M_RCVR) REFERENCES users(USER_ID)
);

CREATE TABLE pinned(
PIN_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
PIN_USER INT NOT NULL,
PIN_FILE INT NOT NULL,
PIN_NICKNAME VARCHAR(50),
FOREGIN KEY pinned(PIN_USER) REFERENCES users(USER_ID),
FOREIGN KEY pinned(PIN_FILE) REFERENCES file(F_ID)
);


CREATE TABLE activity(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
UID INT NOT NULL,
TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ACT_NAME VARCHAR(50) NOT NULL,
ACT_OBJECT VARCHAR(200),
FOREIGN KEY activity(UID) REFERENCES users(USER_ID)
);
-- (ACT_NAME) VALUES('login'),('access'),('download'),('upload'),('query'),('modify'),('pin')

CREATE TABLE ok_files(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
EXT VARCHAR(4) NOT NULL
);
INSERT INTO ok_files (EXT) values('docx'),( 'doc'),( 'ppt'),( 'pptx'),( 'xls'),( 'xlsx'),( 'pdf'),( 'txt'),( 'odt'),( 'ods'),( 'odp'),('psd'),('mp4'),('wmv'),('avi');
INSERT INTO ok_files (EXT) values('avi'),( 'mp4'),( 'wmv'),( 'psd');