CREATE DATABASE IF NOT EXISTS TRADOC;
USE TRADOC;

--TABLE FOR ROLES/ACCESS CONTROL LEVELS
CREATE TABLE ROLE(
ROLE_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ROLE_NAME VARCHAR(20) NOT NULL,
ROLE_DESC VARCHAR(50) NOT NULL
);

INSERT INTO ROLE
VALUES (1,'ADMIN', 'The one assigned to CREATE the user accounts. The only role capable of reading server status and editing the database, with the permission of the OIC'),
(2,'STAFF', 'Can only Upload, View and Download regular files from the server. Also capable of using the LAN Messaging feature.'),
(3,'SUPERUSER', 'Can upload, view and download regular and confidential files. Also capable of using the LAN Messaging feature. Cannot have the privileges of the ADMIN')


--TABLE FOR USERS
CREATE TABLE USER(
USER_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
USER_NAME VARCHAR(20) NOT NULL,
USER_FNAME VARCHAR(30) NOT NULL,
USER_LNAME VARCHAR(30) NOT NULL,
USER_PW VARCHAR(32) NOT NULL,
ROLE_ID INT NOT NULL,
FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

INSERT INTO USER VALUES(USER_NAME, USER_FNAME, USER_LNAME, USER_PW, ROLE_ID)
VALUES ('user01', 'Antonio', 'Luna', '5f4dcc3b5aa765d61d8327deb882cf99',1),
('adminAq', 'Xander', 'Ford', '5f4dcc3b5aa765d61d8327deb882cf99',2),
('general', 'Rodrigo', 'Duterte', '5f4dcc3b5aa765d61d8327deb882cf99',3),


--TABLE FOR FILE
CREATE TABLE FILE(
F_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
F_NAME_ORIG VARCHAR(36) NOT NULL,
F_NAME_SERVER VARCHAR(32) NOT NULL,
F_UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
F_DESC VARCHAR(200),
F_UPLOADER INT NOT NULL,
F_TAGS VARCHAR(200),
FILE_X INT DEFAULT 0,
FOREIGN KEY (F_UPLOADER) REFERENCES USER(USER_ID)
);

--TABLE FOR UPLOAD ACTIVITY
CREATE TABLE ACTIVITY(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
F_ID INT NOT NULL,
FOREIGN KEY (F_ID) REFERENCES FILE(F_ID)
);

--TABLE FOR MESSAGES
CREATE TABLE MESSAGES(
M_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
M_SENDER INT NOT NULL,
M_MSG VARCHAR(200) NOT NULL,
M_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
M_RCVR INT NOT NULL,
FOREIGN KEY (M_SENDER) REFERENCES USER(USER_ID),
FOREIGN KEY (M_RCVR) REFERENCES USER(USER_ID)
);

--TABLE FOR MESSAGE NOTIFICATION STATUS CONTROL
CREATE TABLE MSTATUS(
MS_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
MS_SENDER INT NOT NULL,
MS_RCVR INT NOT NULL,
MS_STATUS INT DEF 0, -- 0 = NO NOTIF, 1 = NEW NOTIF 
FOREIGN KEY (MS_SENDER) REFERENCES USER(USER_ID),
FOREIGN KEY (MS_RCVR) REFERENCES USER(USER_ID)
);

--TABLE FOR USER MESSAGE NOTIFICATION CONTROL
CREATE TABLE SSTATUS(
S_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
S_USER INT NOT NULL,
S_STAT INT DEF 0, -- 0 = NO NOTIF, 1 = NEW NOTIF 
FOREIGN KEY (S_USER) REFERENCES USER(USER_ID)
);

--############################
--##    T R I G G E R S     ##
--############################

--TRIGGER TO CREATE RECORD ON SSTATUS
DELIMITER $
CREATE TRIGGER init_user
AFTER INSERT ON USER
FOR EACH ROW
	INSERT INTO SSTATUS (S_USER)
	VALUES (New.USER_ID);$

DELIMITER ;

--TRIGGER TO RECORD ACTIVITY ON EVERY FILE UPLOAD
DELIMITER $
CREATE TRIGGER upload_action
AFTER INSERT ON FILE
DECLARE x INT DEFAULT 0;
	FOR EACH ROW
	SET x = New.FILE_X
	IF (x < 1) THEN
		INSERT INTO ACTIVITY (F_ID)
		VALUES (New.F_ID);
	END IF;$
DELIMITER ;

--TRIGGER TO CREATE NOTIFICATION ON MESSAGE
DELIMITER $
CREATE TRIGGER msg_sent
AFTER INSERT ON MESSAGE
DECLARE c INT DEFAULT 0;
FOR EACH ROW
	SET c = (SELECT COUNT(*) FROM MSTATUS WHERE M_SENDER=New.M_SENDER and M_RCVR=New.M_RCVR);
	IF (c < 1) THEN
		INSERT INTO M_STATUS (M_SENDER,M_RCVR)
		VALUES (New.M_SENDER, New.M_RCVR);
	ELSE
		UPDATE M_STATUS SET M_STATUS = 1 WHERE M_SENDER = New.M_SENDER AND M_RCVR = New.M_RCVR;
		UPDATE SSTATUS SET S_STAT = 1 WHERE S_USER = New.M_RCVR;
	END IF;$
DELIMITER ;



















